---
- name: Change default ingress certificate
  hosts: localhost
  become: true
  gather_facts: false
  module_defaults:
    kubernetes.core.k8s:
      kubeconfig: /home/snelson/.kube/config
  tasks:
    - name: Update the OperatorHub to disable default sources
      kubernetes.core.k8s:
        state: patched
        api_version: config.openshift.io/v1
        kind: OperatorHub
        name: cluster
        definition:
          spec:
            disableAllDefaultSources: true
